name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        # Configure la clé SSH
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem

        # Déployer sur EC2
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/ec2-user/fastapi-template

          # Arrêter tous les conteneurs Docker en cours
          docker stop $(docker ps -q) || true

          # Supprimer tous les conteneurs Docker arrêtés
          docker rm $(docker ps -a -q) || true

          # Construire et exécuter le nouveau conteneur
          docker build -t my-fastapi-app .
          docker run -d --name my-fastapi-app -p 8000:8000 \
           -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
           -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
           -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
           -e AWS_REGION=${{ secrets.AWS_REGION }} \
           my-fastapi-app
        EOF
